### ISSUE TITLE
request-help: 想做个小工具

### ISSUE THREAD

**Issue by Beckjiang** [thirdgerb/chatbot#2]
感觉可以优化许多流程的交互体验，求开发文档:) 

或者对看源码有什么建议呢（比如，从哪开始？有什么关键概念

**Comment by thirdgerb** [comment]
最近忙着写开发文档和其它事情, 没有及时回复, sorry. 

可以查看官方文档项目: https://github.com/thirdgerb/chatbot-book   
正在努力更新中, 完成后会正式发布.
